WIDTH, HEIGHT = 1200, 800
SPEED = 300
LANES_PER_SIDE = 4
LANE_WIDTH = 40
CAR_LENGTH = 55
PIXELS_PER_METER = 18
LANE_CHANGE_SPEED_THRESHOLD = 5
ROAD_SPEED_LIMIT = 14
ROAD_LENGTH = 700

# IDM
IDM_DELTA = 4

# MOBIL
LANE_CHANGE_COOLDOWN = 2.0
LANE_CHANGE_COOLDOWN_PIXELS = 100
MANDATORY_LC_DISTANCE_PER_LANE_PIXELS = 100
MANDATORY_LC_COOLDOWN = 1.0

# Traffic lights
TRAFFIC_LIGHT_OFFSET = 0
TRAFFIC_RED_YELLOW_TIME = 1
TRAFFIC_YELLOW_TIME = 1
TRAFFIC_GREEN_TIME = 2
TRAFFIC_RED_TIME = 2
TRAFFIC_LIGHT_WIDTH = 20
TRAFFIC_LIGHT_HEIGHT = 40
STOP_OFFSET_METERS = 0.5

# Generator
MIN_SPAWN_GAP_M = 5
INFLOW = 1.8
MAX_SPAWN_TIME = 3
LEFT_PROBABILITY = 0.2
RIGHT_PROBABILITY = 0.3

# Conflicts
SAFE_CONFLICT_GAP_METERS = 2.5 
TIME_BEFORE_CONFLICT = 2
TIME_AFTER_CONFLICT = 1.5
CHECK_CONFLICT_DIST_PIXELS = 100
STOP_CONFLICT_DIST_M = 1
