LANE_WIDTH = 40 
CAR_LENGTH = 55
PIXELS_PER_METER = 18
LANE_CHANGE_SPEED_THRESHOLD = 5

# IDM
IDM_DELTA = 4

# MOBIL
LANE_CHANGE_COOLDOWN = 2.5

# Traffic lights
TRAFFIC_RED_YELLOW_TIME = 1
TRAFFIC_YELLOW_TIME = 1
TRAFFIC_GREEN_TIME = 2
TRAFFIC_RED_TIME = 2
TRAFFIC_LIGHT_WIDTH = 40
TRAFFIC_LIGHT_HEIGHT = 80
STOP_OFFSET_METERS = 2

# Generator
MIN_SPAWN_GAP_M = 5
SPAWN_INTERVAL = 3
