WIDTH, HEIGHT = 1200, 800
SPEED = 300
LANES_PER_SIDE = 4
LANE_WIDTH = 40
CAR_LENGTH = 55
PIXELS_PER_METER = 18
LANE_CHANGE_SPEED_THRESHOLD = 3
ROAD_SPEED_LIMIT = 14
ROAD_LENGTH = 700
SIMULATION_SPEED = 1

# IDM
IDM_DELTA = 4
TIME_HEADWAY = 0.8
MIN_GAP = 1
ACC = 2.5
DCC = 2

# MOBIL 
# standard
POLITENESS = 0.6
SAVE_DCC = 3
ACC_THRESHOLD = 0.8
BIAS = 1
# mandatory
M_POLITENESS = 0.1
M_SAVE_DCC = 3
M_ACC_THRESHOLD = 0
M_BIAS = 10
# others
LANE_CHANGE_COOLDOWN = 2.0
LANE_CHANGE_COOLDOWN_PIXELS_AFTER = 80
LANE_CHANGE_COOLDOWN_PIXELS_BEFORE = 150
MANDATORY_LC_DISTANCE_PER_LANE_PIXELS = 100
MANDATORY_LC_COOLDOWN = 1.5
MANDATORY_LC_CONFLICT_SAFE_GAP_PIXELS = 80
LANE_CHANGE_DURATION_MIN = 0.4
LANE_CHANGE_DURATION_MAX = 1.5

# Traffic lights
TRAFFIC_LIGHT_OFFSET = 0
TRAFFIC_RED_YELLOW_TIME = 1
TRAFFIC_YELLOW_TIME = 1
TRAFFIC_GREEN_TIME = 2
TRAFFIC_RED_TIME = 2
TRAFFIC_LIGHT_WIDTH = 20
TRAFFIC_LIGHT_HEIGHT = 40
STOP_OFFSET_METERS = 0.5

# Generator
MIN_SPAWN_GAP_M = 5
INFLOW = 1.5
MAX_SPAWN_TIME = 3
LEFT_PROBABILITY = 0.2
RIGHT_PROBABILITY = 0.3

# Conflicts
SAFE_CONFLICT_GAP_METERS = 2.5 
TIME_BEFORE_CONFLICT = 1
TIME_AFTER_CONFLICT = 1
CHECK_CONFLICT_DIST_PIXELS = 150
STOP_CONFLICT_DIST_M = 1.5
